### PR TITLE
Linting tweaks

### PR DESCRIPTION
**Pull request by jamescooke**
Two adjustments to linting for conversation.

* Remove ignored pep8 errors.
* Propose an isort config. This isn't wired into CI yet, it could just be used for files that are touched going forwards.

Let me know thoughts.

### CODE REVIEW

**Comment by richerry** [comment]
isort is a great idea to keep imports in order as you go. I'm looking at [coala](http://coala-analyzer.org/) and that's one of the features (everything is a plugin). I've not finished evaluating it yet after seeing it at EuroPython but it can do auto-fixes to the analysis it performs as well and can deal with a variety of languages. It takes config from a .coafile in the project or your ~/.coafile.

I'm hoping it will be one tool to lint them all!

**Comment by bmcorser** [comment]
Can we close or merge this?

@adammalinowski I remember you mentioning the tool this config is for .. is this something that can be added to a standard?

**Comment by adammalinowski** [comment]
Looks sensible to me. 

Good point @bmcorser, I'll make a note to add isort to the standards doc.

**Comment by jamescooke** [comment]
Thanks for merge @adammalinowski :+1:

**Pull request merged**
